[project]
name = "parity"
version = "0.1.0"
description = "App description"
authors = [
    { name = "wilfried-oss", email = "davowilfried3@gmail.com" }
]
requires-python = ">=3.12"
dependencies = [
    "fastapi>=0.141.1",
    "httpx2>=2.10.0",
    "pydantic>=2.13.4",
    "pytest>=9.1.1",
    "ruff>=0.16.2",
    "uvicorn>=0.52.1",
]

[project.scripts]
parity = "parity:main"

[build-system]
requires = ["uv_build>=0.12.2,<0.13.0"]
build-backend = "uv_build"
